[phases.setup]
nixPkgs = ["python312", "glib", "nss", "nspr", "atk", "cups", "gtk3", "pango", "cairo", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "xorg.libXfixes"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install chromium"
]