[variables]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]